/* MTI_DPI */

/*
 * Copyright 2002-2006 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux'
 */
#ifndef INCLUDED_DPI_TYPES
#define INCLUDED_DPI_TYPES

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
int
doit(
    int val);

DPI_LINK_DECL void
Double(
    int num_in,
    int* num_out);

#endif 
